# Generated by Django 4.1 on 2023-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayurvedicjuice',
            name='picture',
            field=models.ImageField(upload_to='static/images/AyurvedicJuice/'),
        ),
    ]
