# Generated by Django 4.2.4 on 2023-11-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='users',
        ),
        migrations.AddField(
            model_name='promocode',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_amount',
            field=models.IntegerField(default=1500),
        ),
    ]
