# Generated by Django 4.2.4 on 2023-09-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamingummies',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
