# Generated by Django 4.2.4 on 2023-11-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0002_remove_promocode_users_promocode_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user_email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
