# Generated by Django 4.2.4 on 2023-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0003_alter_promocode_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
