<<<<<<< HEAD
# Generated by Django 4.1 on 2023-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0004_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=4000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
=======
# Generated by Django 4.1 on 2023-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0004_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=4000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
>>>>>>> 5ad53f314d49550da0ac941b381d9aa8e0654a71
