# Generated by Django 4.2.4 on 2023-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0004_alter_vitamingummies_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayurvedicjuice',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ayurvedicpower',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='effervescenttablets',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tropicalskinhair',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vitamincapsules',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
