# Generated by Django 4.2.4 on 2023-11-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0004_alter_promocode_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='user_email',
            new_name='email',
        ),
    ]
