# Generated by Django 4.2.4 on 2023-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0005_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBuyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
