# Generated by Django 4.2.4 on 2023-11-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0006_alter_promocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
