# Generated by Django 4.2.4 on 2023-08-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0006_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
