# Generated by Django 4.2.4 on 2023-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0007_remove_user_data_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
