# Generated by Django 4.2.4 on 2023-11-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0007_alter_promocode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='email',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
