# Generated by Django 4.2.4 on 2023-11-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0008_alter_promocode_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='email',
            new_name='userName',
        ),
    ]
