# Generated by Django 4.2.4 on 2023-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0008_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
