# Generated by Django 4.2.4 on 2023-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0009_user_data_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
