# Generated by Django 4.2.4 on 2023-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0009_size_ayurvedicjuice_image_ayurvedicpower_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitamingummies',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
