# Generated by Django 4.2.4 on 2023-11-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0009_rename_email_promocode_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='userName',
        ),
    ]
