# Generated by Django 4.2.4 on 2023-11-16 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0010_remove_promocode_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeVerify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount', models.IntegerField(default=0)),
                ('min_amount', models.IntegerField(default=1500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
