# Generated by Django 4.2.4 on 2023-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0010_alter_user_data_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBuyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
