# Generated by Django 4.2.4 on 2023-08-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0006_productbuydetails'),
        ('Hydrations', '0010_alter_user_data_phone_number'),
    ]

    operations = [
    ]
