# Generated by Django 4.2.4 on 2023-09-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0010_alter_vitamingummies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitamingummies',
            name='description',
            field=models.TextField(),
        ),
    ]
