# Generated by Django 4.2.4 on 2023-10-10 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0011_alter_vitamingummies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribed_user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
