# Generated by Django 4.2.4 on 2023-08-15 21:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0011_merge_20230816_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuydetails',
            name='email',
            field=models.EmailField(default=builtins.dir, max_length=254),
            preserve_default=False,
        ),
    ]
