# Generated by Django 4.2.4 on 2023-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0011_promocodeverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('address_1', models.CharField(default='', max_length=1000)),
                ('products_detail', models.JSONField(null=True)),
                ('order_total', models.IntegerField(default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
