# Generated by Django 4.2.4 on 2023-09-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0012_alter_ayurvedicjuice_id_alter_ayurvedicpower_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBuyDetails',
        ),
        migrations.RenameField(
            model_name='ayurvedicjuice',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='ayurvedicpower',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='effervescenttablets',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='tropicalskinhair',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='vitamincapsules',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.RenameField(
            model_name='vitamingummies',
            old_name='quantity',
            new_name='max_quantity',
        ),
    ]
