# Generated by Django 4.2.4 on 2023-11-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0012_cart_data_delete_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeverify',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promocodeverify',
            name='min_amount',
        ),
    ]
