# Generated by Django 4.2.4 on 2023-08-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0011_productbuydetails'),
        ('Hydrations', '0012_productbuydetails_email'),
    ]

    operations = [
    ]
