# Generated by Django 4.2.4 on 2023-09-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0012_productbuydetails_email'),
        ('Hydrations', '0013_delete_productbuydetails_and_more'),
    ]

    operations = [
    ]
