# Generated by Django 4.2.4 on 2023-09-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0014_merge_20230904_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(editable=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('order_total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductBuyDetails',
        ),
    ]
