# Generated by Django 4.2.4 on 2023-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0015_orders_delete_productbuydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='products_detail',
            field=models.CharField(default='empty', max_length=1000),
        ),
    ]
