# Generated by Django 4.2.4 on 2023-09-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0016_remove_orders_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email_id',
            new_name='email',
        ),
    ]
