# Generated by Django 4.2.4 on 2023-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0017_rename_email_id_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_picture',
            field=models.ImageField(default='', upload_to='static/images/VitaminCapsules/'),
        ),
    ]
