# Generated by Django 4.2.4 on 2023-09-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0018_orders_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_picture',
        ),
        migrations.AddField(
            model_name='orders',
            name='address_1',
            field=models.CharField(default='INDIA', max_length=1000),
        ),
    ]
