# Generated by Django 4.2.4 on 2023-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hydrations', '0019_remove_orders_product_picture_orders_address_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='state',
            field=models.CharField(default='GUJRAT', max_length=100),
        ),
    ]
